name: StudentCrud CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Restore dependencies
      - name: Restore
        run: dotnet restore

      # 4. Build project
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # 5. Run NUnit tests + Code Coverage
      - name: Test with Code Coverage
        run: |
          dotnet test \
            --no-build \
            --configuration Release \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults

      # 6. Install ReportGenerator
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      # 7. Generate HTML Coverage Report
      - name: Generate Coverage Report
        run: |
          reportgenerator \
            -reports:"./TestResults/**/coverage.cobertura.xml" \
            -targetdir:"./CoverageReport" \
            -reporttypes:"Html"

      # 8. Upload Coverage Report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: CoverageReport

      # 9. Upload raw coverage file
      - name: Upload Coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: TestResults
