name: .NET CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-test-deploy:

    runs-on: [self-hosted, first]

    steps:

      # 1. Get latest code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Restore NuGet packages
      - name: Restore
        run: dotnet restore .\StudentCRUD\StudentCRUD.csproj

      # 4. Build project
      - name: Build
        run: dotnet build .\StudentCRUD\StudentCRUD.csproj --configuration Release --no-restore

      # 5. Run tests
      - name: Test
        run: dotnet test --configuration Release --no-build

      # 6. Publish application
      - name: Publish
        run: dotnet publish .\StudentCRUD\StudentCRUD.csproj --configuration Release --output C:\StudentCRUD-Deploy

      # 7. Deployment confirmation
      - name: Deployment Completed
        run: |
          Write-Host "======================================"
          Write-Host " StudentCRUD CI/CD Deployment Success "
          Write-Host "======================================"
          Write-Host "Deployment Folder:"
          Write-Host "C:\StudentCRUD-Deploy"
```
